import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'button/index': 'src/button/index.tsx',
    'slot/index': 'src/slot/index.tsx',
    'input/index': 'src/input/index.tsx',
    'card/index': 'src/card/index.tsx',
    'badge/index': 'src/badge/index.tsx',
    'spinner/index': 'src/spinner/index.tsx',
    'switch/index': 'src/switch/index.tsx',
    'checkbox/index': 'src/checkbox/index.tsx',
    'avatar/index': 'src/avatar/index.tsx',
    'tooltip/index': 'src/tooltip/index.tsx',
    'dialog/index': 'src/dialog/index.tsx',
    'textarea/index': 'src/textarea/index.tsx',
    'tag/index': 'src/tag/index.tsx',
    'progress/index': 'src/progress/index.tsx',
    'skeleton/index': 'src/skeleton/index.tsx',
    'divider/index': 'src/divider/index.tsx',
    'alert/index': 'src/alert/index.tsx',
    'tabs/index': 'src/tabs/index.tsx',
    'radio-group/index': 'src/radio-group/index.tsx',
    'accordion/index': 'src/accordion/index.tsx',
    'breadcrumb/index': 'src/breadcrumb/index.tsx',
    'pagination/index': 'src/pagination/index.tsx',
    'select/index': 'src/select/index.tsx',
    'slider/index': 'src/slider/index.tsx',
    'toast/index': 'src/toast/index.tsx',
    'menu/index': 'src/menu/index.tsx',
    'table/index': 'src/table/index.tsx',
    'drawer/index': 'src/drawer/index.tsx',
    // New components
    'visually-hidden/index': 'src/visually-hidden/index.tsx',
    'portal/index': 'src/portal/index.tsx',
    'label/index': 'src/label/index.tsx',
    'aspect-ratio/index': 'src/aspect-ratio/index.tsx',
    'kbd/index': 'src/kbd/index.tsx',
    'code/index': 'src/code/index.tsx',
    'collapsible/index': 'src/collapsible/index.tsx',
    'scroll-area/index': 'src/scroll-area/index.tsx',
    'form-field/index': 'src/form-field/index.tsx',
    'resizable/index': 'src/resizable/index.tsx',
    'stat/index': 'src/stat/index.tsx',
    'rating/index': 'src/rating/index.tsx',
    'timeline/index': 'src/timeline/index.tsx',
    'tree/index': 'src/tree/index.tsx',
    'carousel/index': 'src/carousel/index.tsx',
    'popover/index': 'src/popover/index.tsx',
    'hover-card/index': 'src/hover-card/index.tsx',
    'alert-dialog/index': 'src/alert-dialog/index.tsx',
    'context-menu/index': 'src/context-menu/index.tsx',
    'command/index': 'src/command/index.tsx',
    'stepper/index': 'src/stepper/index.tsx',
    'navigation-menu/index': 'src/navigation-menu/index.tsx',
    'number-input/index': 'src/number-input/index.tsx',
    'pin-input/index': 'src/pin-input/index.tsx',
    'file-upload/index': 'src/file-upload/index.tsx',
    'combobox/index': 'src/combobox/index.tsx',
    'calendar/index': 'src/calendar/index.tsx',
    'date-picker/index': 'src/date-picker/index.tsx',
    'color-picker/index': 'src/color-picker/index.tsx',
  },
  format: ['esm'],
  dts: true,
  sourcemap: true,
  clean: true,
  treeshake: true,
  splitting: false,
  external: ['react', 'react-dom'],
  esbuildOptions(options) {
    options.banner = {
      js: '"use client";',
    };
  },
});
