import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'button/index': 'src/button/index.tsx',
    'slot/index': 'src/slot/index.tsx',
    'input/index': 'src/input/index.tsx',
    'card/index': 'src/card/index.tsx',
    'badge/index': 'src/badge/index.tsx',
    'spinner/index': 'src/spinner/index.tsx',
    'switch/index': 'src/switch/index.tsx',
    'checkbox/index': 'src/checkbox/index.tsx',
    'avatar/index': 'src/avatar/index.tsx',
    'tooltip/index': 'src/tooltip/index.tsx',
    'dialog/index': 'src/dialog/index.tsx',
    'textarea/index': 'src/textarea/index.tsx',
    'tag/index': 'src/tag/index.tsx',
    'progress/index': 'src/progress/index.tsx',
    'skeleton/index': 'src/skeleton/index.tsx',
    'divider/index': 'src/divider/index.tsx',
    'alert/index': 'src/alert/index.tsx',
    'tabs/index': 'src/tabs/index.tsx',
    'radio-group/index': 'src/radio-group/index.tsx',
    'accordion/index': 'src/accordion/index.tsx',
    'breadcrumb/index': 'src/breadcrumb/index.tsx',
    'pagination/index': 'src/pagination/index.tsx',
    'select/index': 'src/select/index.tsx',
    'slider/index': 'src/slider/index.tsx',
    'toast/index': 'src/toast/index.tsx',
    'menu/index': 'src/menu/index.tsx',
    'table/index': 'src/table/index.tsx',
    'drawer/index': 'src/drawer/index.tsx',
  },
  format: ['esm'],
  dts: true,
  sourcemap: true,
  clean: true,
  treeshake: true,
  splitting: false,
  external: ['react', 'react-dom'],
  esbuildOptions(options) {
    options.banner = {
      js: '"use client";',
    };
  },
});
